apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
  namespace: shop
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: siddhi/spring-boot:catalog
        ports:
        - containerPort: 8080

